// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJlQ4vBBtacAfDfYMxcrhL27cvGJRXRlM',
    appId: '1:428286062397:web:913df82cb58a3879049f54',
    messagingSenderId: '428286062397',
    projectId: 'tasks-eduardo-firabase',
    authDomain: 'tasks-eduardo-firabase.firebaseapp.com',
    storageBucket: 'tasks-eduardo-firabase.firebasestorage.app',
    measurementId: 'G-HZQG2QWJDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLzr8sfRwdst8xjhFH3d4lWyf9vlPvW1s',
    appId: '1:428286062397:android:87796660d6c6b43e049f54',
    messagingSenderId: '428286062397',
    projectId: 'tasks-eduardo-firabase',
    storageBucket: 'tasks-eduardo-firabase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByE5sbGJ9qqbjndLCdkopOkHyKaqFS2Xs',
    appId: '1:428286062397:ios:4f643a2aae4208ff049f54',
    messagingSenderId: '428286062397',
    projectId: 'tasks-eduardo-firabase',
    storageBucket: 'tasks-eduardo-firabase.firebasestorage.app',
    iosBundleId: 'com.eduardo.todolist.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByE5sbGJ9qqbjndLCdkopOkHyKaqFS2Xs',
    appId: '1:428286062397:ios:4f643a2aae4208ff049f54',
    messagingSenderId: '428286062397',
    projectId: 'tasks-eduardo-firabase',
    storageBucket: 'tasks-eduardo-firabase.firebasestorage.app',
    iosBundleId: 'com.eduardo.todolist.todoList',
  );
}
